data:
  dataset: "us_images"
  image_size: 256      # model and input both 256×256
  channels: 1          # grayscale
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: true
  num_workers: 1
  subset_1k: false     # not using ImageNet subsets
  out_of_dist: false

model:
  type: "openai"
  in_channels: 1       # match grayscale input
  out_channels: 1
  num_channels: 256
  num_heads: 4
  num_res_blocks: 2
  attention_resolutions: "32,16,8"
  dropout: 0.0
  resamp_with_conv: true
  learn_sigma: true
  use_scale_shift_norm: true
  use_fp16: false
  resblock_updown: true
  num_heads_upsample: -1
  var_type: "fixedsmall"
  num_head_channels: 64
  image_size: 256      # match data.image_size
  class_cond: false    # no class conditioning
  degradation: true
  known_GT: true       # if you’re feeding GT into the pipeline

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

sampling:
  batch_size: 1
  last_only: true
